---
- name: "Mein erstes Play"
  hosts: all
  gather_facts: "false"
  tasks:
    - name: "Lege den Benutzer Patrick an"
      user:
        name: "patrick"
        uid: "1002"
        state: "present"
    - name: "Lege den Benutzer Pawel an"
      user:
        name: "pawel"
        uid: "1000"
        state: "present"
    - name: "Lege den Benutzer Peter an"
      user:
        name: "peter"
        uid: "1001"
        state: "present"
#    - name: "Lege den Benutzer ansible an"
#      user:
#        name: "ansible"
#        uid: "1005"
#        state: "present"
#        password: "$6$NM0zpvfPqL2R9yE2$46WfMXRBivDodOWHN64EJj3oXQz513OMsDS0RhOAYuz7SEc8gPejKzfK39H.DsRebaMPb7ym2urT2KJVS424n."
    - name: "Sudoers anpassen"
      become: "true"
      lineinfile:
        path: "/etc/sudoers"
        state: "present"
        line: "%ansible        ALL=(ALL)       ALL"

#    - name: "Kopiere test-datei auf managed-hosts"
#      copy:
#        src: "./test-datei.txt"
#        dest: "/root/abgelegte-datei.txt"
#    - name: "Install some software"
#      yum:
#        name:
#          - "epel-release"
#          - "wget"
#          - "yamllint"
#        state: present
...
