---
- name: "Create Users in loop"
  hosts: all
  gather_facts: "false"
  tasks:
    - name: "Lege die Benutzer in einer Loop an"
      user:
        name: "{{item}}"
        #uid: "1000"
        password: "$6$b.i4Ov06s4b3Z8kX$PkO3lGzJVBs9cr63pUa80iNSh4wlZ6DlrLDBKWlDfE.mP.3Lgf67EYS.uF//HrlU2K4BAoMbqeal.AK4inzWD1"
        state: "present"
      with_items:
        - "user1"
        - "user2"
        - "user3"
        - "user4"
        - "user5"
...
