---
- name: "Playbook"
  hosts: all
  gather_facts: "false"
  tasks:
    - name: "Create working directories"
      file: 
        path: "{{ item }}"
        state: "directory"
      with_items:
        - "/opt/sva"

    - name: "03 - Download terraform"
      get_url:
        url: "https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip"
        dest: "/opt/sva/"
...
